-- Nemesis, the Aerials Fumen Workflow
-- Copyright(c) 2025- 1dealGas, under the Apache 2.0 License.
--
local HEADER, NIL = [[
local A = Arf4
local STATIC, LINEAR, INSINE, OUTSINE,_NA = 0,1,2,3, assert
local function _NW(x) return function(y) return _NA(x(y)) end end
local Helper, Delta, Time =_NW(A.NewHelper),_NW(A.SetDelta),_NW(A.NewBuild)
local Wish, Child, Hint, Echo =_NW(A.NewWish),_NW(A.NewChild),_NW(A.NewHint),_NW(A.NewEcho)
local SinceTone, Toneof, CosSin, Log, A = A.SinceTone, A.ConvTime, A.CosSin, Log;
]], function() end


-- Env & Audio
--
local Title = "Nemesis"
local WorksCmd, FumenLoaded   -- FumenLoaded: A Closure to reload the Fumen if updated. Nullable.
local Info = msg.url("Nm:/Viewer#[Info]")

local Audio, AudioLen, AudioPlaying
local PlayUnit, StopUnit = AcAudio.PlayUnit, AcAudio.StopUnit
local HitSounds, HsWhich = {}, 1

local function LoadAudio(basePath)
	for _, ext in ipairs{ ".opus", ".mp3", ".wav" } do
		local ok, data = AcAudio.CreateSource(basePath..ext)
		if ok then
			return AcAudio.CreateUnit(data)
		end
	end
end


-- Canvas & Fumen
--
local CanvasMs, ObjectCount = 0, 0
local CamSeries, CamVals, LogQueue = {}, {}, {}

local Wcnt, Hcnt, Ecnt, Acnt, Vcnt = 0, 0, 0, 0, 0
local WGOs, HGOs, EGOs, XGOs, AlGOs, ArGOs = {}, {}, {}, {}, {}, {}
local WishSprites, HintSprites, EchoSprites, HelpSprites, AlSprites, ArSprites = {}, {}, {}, {}, {}, {}
local WishTints, WishSpecial, HintTints, EchoTints, HelpTints, AnimTints = {}, {}, {}, {}, {}, {}
local LastWused, LastHused, LastEused, LastEhused, LastAused = 0, 0, 0, 0, 0

local ETS, S0, S1 = { [0] = "STATIC", "LINEAR", "INSINE", "OUTSINE" }, Arf4.NewSeries{0,0}, Arf4.NewSeries{0,1}
local ENABLE, DISABLE, TINTW, TINT, NM = hash "enable", hash "disable", hash "tint.w", hash "tint", hash "Nm"
local SPRITE, WISHSP, WISH, ECHO, ANIM = hash "Sprite", hash "WishSP", hash "Wish", hash "Echo", hash "Anim"

local ConvTime, UpdateArf, SetCam, Ease = Arf4.ConvTime, Arf4.UpdateArf, Arf4.SetCam, Arf4.Ease
local go_set, msg_post, sprite_play_flipbook = go.set, msg.post, sprite.play_flipbook
local label_set_text, string_format = label.set_text, string.format

local function EnqueueLog(t, name)
	if t[2] then
		LogQueue[ t.Name or name or os.clock() ] = t
			for i = 1, #t, 3 do
				t[i] = ConvTime(  ConvTime( t[i] ),  2  )   -- [0] toTone  [1] barToMs  [2] toneToMs
			end
		return true
	end
end

local function Cam(i, name)
	return function(t)
		if EnqueueLog(t, name) then
			CamSeries[i] = Arf4.NewSeries(t)
		end
	end
end

local function UpdateCanvas(MS, playHs)
	Ease(MS, CamSeries, CamVals)
	SetCam(CamVals[1], CamVals[2], CamVals[3], CamVals[4])
	local wu, hu, eu, xu, au, hp, ep = UpdateArf(MS, 30, WishTints, HelpTints)

	-- Args
	--
	if not wu then
		wu, hu, eu, xu, au, hp, ep = 0, 0, 0, 0, 0, false, false
	end

	for i = 1, wu do
		local wishSprite, wishTint = WishSprites[i], WishTints[i]
		local isSpecial, lastSpecial = wishTint < 0, WishSpecial[i]
		go_set(wishSprite, TINTW, isSpecial and -wishTint or wishTint)

		if isSpecial ~= lastSpecial then
			sprite_play_flipbook(wishSprite, isSpecial and WISHSP or WISH)
			WishSpecial[i] = isSpecial
		end
	end

	for i = 1, hu do	go_set(HintSprites[i], TINT, HintTints[i])		end
	for i = 1, eu do	go_set(EchoSprites[i], TINT, EchoTints[i])		end
	for i = 1, xu do	go_set(HelpSprites[i], TINTW, HelpTints[i])		end
	for i = 1, au do	go_set(AlSprites[i], TINT, AnimTints[i])
						go_set(ArSprites[i], TINT, AnimTints[i])		end

	-- Enable / Disable, Misc
	--
	for i = LastWused+1, wu do	msg_post(WishSprites[i], ENABLE)		end
	for i = wu+1, LastWused do	msg_post(WishSprites[i], DISABLE)		end

	for i = LastHused+1, hu do	msg_post(HintSprites[i], ENABLE)		end
	for i = hu+1, LastHused do	msg_post(HintSprites[i], DISABLE)		end

	for i = LastEused+1, eu do	msg_post(EchoSprites[i], ENABLE)		end
	for i = eu+1, LastEused do	msg_post(EchoSprites[i], DISABLE)		end

	for i = LastEhused+1, xu do	msg_post(HelpSprites[i], ENABLE)		end
	for i = xu+1, LastEhused do	msg_post(HelpSprites[i], DISABLE)		end

	for i = LastAused+1, au do	msg_post(AlSprites[i], ENABLE)
								msg_post(ArSprites[i], ENABLE)			end
	for i = au+1, LastAused do	msg_post(AlSprites[i], DISABLE)
								msg_post(ArSprites[i], DISABLE)			end

	CanvasMs, LastWused, LastHused, LastEused, LastEhused, LastAused = MS, wu, hu, eu, xu, au
	label_set_text(Info, string_format(
		"·][·  %u of %u ms · %u Object(s) : %u", MS, AudioLen, ObjectCount, Vcnt
	))

	if playHs and (hp or ep) then
		PlayUnit(HitSounds[HsWhich], false)
		HsWhich = (HsWhich == 32) and 1 or (HsWhich+1)
		StopUnit(HitSounds[HsWhich], true)
	end
end

local function AllocCanvas(wReq, hReq, eReq)
	local create, vector4, url = factory.create, vmath.vector4, msg.url
	local Wishc, Hintc, Helc = url("Viewer#Wishc"), url("Viewer#Hintc"), url("Viewer#Helc")
	local aReq, dels, dx = hReq + eReq, {}, 1
--------
	for i = Wcnt+1, wReq do
		local W = create(Wishc)
		WGOs[i], WishSprites[i] = W, url(NM, W, SPRITE)								end
	for i = wReq+1, Wcnt do
		dels[dx], dx = WGOs[i], (dx+1)												end

	for i = Hcnt+1, hReq do
		local H = create(Hintc, nil, nil, nil, 1.237)
		HGOs[i], HintSprites[i], HintTints[i] = H, url(NM, H, SPRITE), vector4(1)	end
	for i = hReq+1, Hcnt do
		dels[dx], dx = HGOs[i], (dx+1)												end

	for i = Ecnt+1, eReq do
		local EH, ES = create(Helc), url( NM, create(Wishc), SPRITE )
		EGOs[i], EchoSprites[i], EchoTints[i] = ES.path, ES, vector4()
		XGOs[i], HelpSprites[i] = EH, url(NM, EH, SPRITE)
		sprite_play_flipbook(ES, ECHO)												end
	for i = eReq+1, Ecnt do
		dels[dx], dels[dx+1], dx = EGOs[i], XGOs[i], (dx+2)							end

	for i = Acnt+1, aReq do
		local ALS = url(NM, create(Hintc), SPRITE)
		local ARS = url(NM, create(Hintc), SPRITE)
		AlGOs[i], AlSprites[i] = ALS.path, ALS  ;  sprite_play_flipbook(ALS, ANIM)
		ArGOs[i], ArSprites[i] = ARS.path, ARS  ;  sprite_play_flipbook(ARS, ANIM)
		AnimTints[i] = vector4()													end
	for i = aReq+1, Acnt do
		dels[dx], dels[dx+1], dx = AlGOs[i], ArGOs[i], (dx+2)						end
--------
	Wcnt, Hcnt, Ecnt, Acnt, Vcnt = wReq, hReq, eReq, aReq, wReq + aReq ; go.delete(dels)
	LastWused, LastHused, LastEused, LastEhused, LastAused = wReq, hReq, eReq, eReq, aReq
	Arf4.Bind(WGOs, HGOs, EGOs, XGOs, AlGOs, ArGOs, HintTints, EchoTints, AnimTints)
	UpdateCanvas(CanvasMs)
end

local function CreateNlenv()
	local G = {}
	G.Arf4, G.bit, G.math, G.string, G.table = Arf4, bit, math, string, table
	G.assert, G.pairs, G.ipairs, G.next, G.pprint = assert, pairs, ipairs, next, pprint
	G.print, G.select, G.tonumber, G.tostring, G.type, G.unpack = print, select, tonumber, tostring, type, unpack
	G.Log, G.Xs, G.Ys, G.Xd, G.Cs = EnqueueLog, Cam(1, "Xs"), Cam(2, "Ys"), Cam(3, "Xd"), Cam(4, "Cs")
	CamSeries, LogQueue = {S1, S1, S0, S1}, {}
	return G
end

local function CreateReload(PATH, LoadFn)
	local lastModification = Arf4.GetFileMtime(PATH)
--------
	return function()
		local modification = Arf4.GetFileMtime(PATH)
		if not modification then   -- *.ar deleted
			FumenLoaded = NIL
			return false, "·][· File Listening Aborted"
		elseif modification ~= lastModification then
			lastModification = modification
			return LoadFn(PATH, false)
		end
	end
end

local function LoadFumenAr(PATH, isBoot)
	local b, o, w, h, e = Arf4.LoadArf(PATH)
	if not b then
		return false, "·][· Arf4: Failed to Load the Fumen"
	end

	ObjectCount, CamSeries = o, {S1, S1, S0, S1} ; AllocCanvas(w, h, e)
	return isBoot and CreateReload(PATH, LoadFumenAr) or true
end

local function LoadFumenNm(PATH, isBoot)
	local scriptFile = io.open(PATH)
	local scriptCompiled, scriptErr = loadstring( scriptFile and HEADER .. scriptFile:read("*a") or PATH )
	if not scriptCompiled then
		return false, "·][· Lua " .. scriptErr
	end

	local callOk, callErr = pcall(setfenv( scriptCompiled, CreateNlenv() ))
	if not callOk then
		return false, "·][· Lua " .. callErr
	end

	local b, o, w, h, e = Arf4.OrganizeArf()
	if not b then
		return false, "·][· " .. o
	end

	ObjectCount = o ; AllocCanvas(w, h, e)
	return isBoot and CreateReload(PATH, LoadFumenNm) or true
end


-- UI & Actions
--
local ProjectName = ""
local COLOR, BLACK, GREY = hash "color", vmath.vector4(0, 0, 0, 1), vmath.vector4(0.37, 0.37, 0.37, 1)
local InputLabel, InputText, InputMode = msg.url("Nm:/Buttons#L1-Input"), "", false

local WindowCenterX, WindowCenterY, WindowRatio = 900, 540, 1
local CtrlPressed, AltPressed, ButtonPressed = false, false, nil
local Panels, Bdy, ButtonXs = nil, 20, {   -- Y range [20,70] or [-70,-20]
	24, 224,			248, 348,			372, 459.5,			483.5, 558.5,
	1278, 1428,			1452, 1602,			1626, 1776
}

local ButtonFns = {
	[1] = function()   -- Args Input
		InputMode, InputText = true, ""
		go_set(Panels[1], TINTW, 0.88) ; go_set(InputLabel, COLOR, GREY)
		label_set_text(InputLabel, "Args Input")
	end,

	[2] = function()   -- Load
		if AudioPlaying then return end
		local pBase = sys.get_save_file("Nemesis Works", InputText)
	--------
		local A1, A2 = LoadAudio(pBase)
			if not A1 then
				label_set_text(Info, "·][· Audio (*.opus/*.mp3/*.wav) Not Loaded")
			return end
		Audio, AudioLen, CanvasMs = A1, A2, 0
	--------
		for Ext, loadFn in pairs{  [".lua"] = LoadFumenNm,  [".ar"] = LoadFumenAr  } do
			if Arf4.GetFileMtime( pBase .. Ext ) then
				local L1, L2 = loadFn(pBase .. Ext, true)
				if L1 then
					ProjectName, FumenLoaded = InputText, L1
					window.set_title( string_format("%s -- %s%s", Title, ProjectName, Ext) )
				else
					Audio, AudioLen = nil, nil
					label_set_text(Info, L2)
				end
			return end
		end
	--------
		label_set_text(Info, "·][· Script File Not Found")
	end,

	[3] = function()   -- Bar
		if FumenLoaded and (not AudioPlaying) then
			UpdateCanvas(vmath.clamp(  ConvTime(InputText, 1),  0,  AudioLen - 10  ))
		end
	end,

	[4] = function()   -- Ms
		if FumenLoaded and (not AudioPlaying) then
			UpdateCanvas(vmath.clamp(  tonumber(InputText) or 0,  0,  AudioLen - 10  ))
		end
	end,

	[5] = function()   -- Export
		if FumenLoaded then
			local basePath = sys.get_save_file("Nemesis Works", string.format( "%s - %s",  ProjectName,  os.date"%g%m%d" ))
				io.output( next(LogQueue)  and  basePath..".series"  or  io.stdout )   -- Export Series Log
					for name, kf in pairs(LogQueue) do
						io.write( name .. " {" )
							for i = 1, #kf, 3 do
								io.write(string_format( "\n	%u, %s, %s,", kf[i], kf[i+1], ETS[ kf[i+2] ] or "UNKNOWN" ))
							end
						io.write( "\n}\n" )
					end
				io.close()
			local fmfile = io.open(basePath..".ar", "wb")
				if fmfile then
					fmfile:write(  Arf4.ExportArf()  )
					fmfile:close()
				end
			os.execute(WorksCmd)
		end
	end,

	[6] = function()  -- Works
		os.execute(WorksCmd)
	end,

	[7] = function()  -- Play & Pause
		if FumenLoaded then
			if AudioPlaying then
				StopUnit(Audio, false)
			else
				AcAudio.SetTime(Audio, CanvasMs)
				PlayUnit(Audio, false)
			end
		end
	end
}

local function ButtonOnWhich(x, y)
	if (y >= Bdy) and (y <= Bdy + 50) then
		for i = 1, 7 do
			if x <= ButtonXs[i*2] and x >= ButtonXs[i*2-1] then
				return i
			end
		end
	end
end

local function ProcessButtons(action)
	if action.pressed then
		ButtonPressed = ButtonOnWhich(
			900 + (action.screen_x - WindowCenterX) * WindowRatio,
			540 + (action.screen_y - WindowCenterY) * WindowRatio
		)
		if ButtonPressed then
			go_set(Panels[ButtonPressed], TINTW, 1)
		end
	elseif action.released and ButtonPressed then
		go_set(Panels[ButtonPressed], TINTW, 0.73)
		ButtonPressed = ButtonPressed == ButtonOnWhich(
			900 + (action.screen_x - WindowCenterX) * WindowRatio,
			540 + (action.screen_y - WindowCenterY) * WindowRatio
		) and ButtonFns[ButtonPressed]()
	end
end

local InputModeFns = {
	[hash"text"] = function(action)
		if InputText == "" then
			go_set(InputLabel, COLOR, BLACK)
		end
		InputText = InputText .. action.text
		label_set_text( InputLabel, #InputText>13 and InputText:sub(1,11).."··" or InputText )
	end,

	[hash"backspace"] = function(action)
		if action.pressed or action.repeated then
			InputText = string.sub(InputText, 1, -2)
			if InputText == "" then
				go_set(InputLabel, COLOR, GREY)
				label_set_text(InputLabel, "Args Input")
			else
				label_set_text( InputLabel, #InputText>13 and InputText:sub(1,11).."··" or InputText )
			end
		end
	end,

	[hash"touch"] = function(action)
		if action.released then
			if InputText == "SHOWBG" then		msg_post(".", ENABLE)  ; Bdy =  20 ; go_set("Buttons", "position.y",   0)
			elseif InputText == "HIDEBG" then	msg_post(".", DISABLE) ; Bdy = -70 ; go_set("Buttons", "position.y", -90)
			end									InputMode = go_set(Panels[1], TINTW, 0.73)
		end										ProcessButtons(action)
	end
}

local ActionFns = {
	[hash"touch"] = ProcessButtons,
	[hash"ctrl"] = function(action)		CtrlPressed = not action.released		end,
	[hash"alt"] = function(action)		AltPressed = not action.released		end,

	[hash"up"] = function(action)
		if FumenLoaded and (not AudioPlaying) and (action.pressed or action.repeated) then
			local t = (CtrlPressed or AltPressed) and (CanvasMs - 370) or (CanvasMs - 37)
			UpdateCanvas(  (t > 0) and t or 0  )
		end
	end,

	[hash"down"] = function(action)
		if FumenLoaded and (not AudioPlaying) and (action.pressed or action.repeated) then
			local t = (CtrlPressed or AltPressed) and (CanvasMs + 370) or (CanvasMs + 37)
			UpdateCanvas(  (t < AudioLen-10) and t or AudioLen-10  )
		end
	end,

	[hash"wheel_up"] = function(action)
		if FumenLoaded and (not AudioPlaying) and (action.value == 1) then
			local t = (CtrlPressed or AltPressed) and (CanvasMs - 370) or (CanvasMs - 37)
			UpdateCanvas(  (t > 0) and t or 0  )
		end
	end,

	[hash"wheel_down"] = function(action)
		if FumenLoaded and (not AudioPlaying) and (action.value == 1) then
			local t = (CtrlPressed or AltPressed) and (CanvasMs + 370) or (CanvasMs + 37)
			UpdateCanvas( (t < AudioLen-10) and t or AudioLen-10 )
		end
	end
}


-- Lifecycle
--
local LastPlaying = nil
local CheckPlaying, GetTime = AcAudio.CheckPlaying, AcAudio.GetTime
function init()
	msg_post("#", "acquire_input_focus")															-- Window & UI
	window.set_listener( function(_, event, data)
		if event == 2 then   -- Input Adjusting
			WindowCenterX, WindowCenterY = data.width / 2, data.height / 2
			WindowRatio = 1 / math.min( WindowCenterX / 900, WindowCenterY / 540 )
		elseif event == 1 and FumenLoaded then   -- File Listening
			local _, einf = FumenLoaded()
			if einf then	label_set_text( Info, einf )
			end
		end
	end )

	local m, n = window.get_size()
	window.set_position( m/2 - 900, n/2 - 540 )
	window.set_size(1800, 1080)

	local url = msg.url
		Panels = {	url "Nm:/Buttons#P1-Input",		url "Nm:/Buttons#P2-Load",		url "Nm:/Buttons#P3-Bar",
					url "Nm:/Buttons#P4-Ms",		url "Nm:/Buttons#P5-Export",	url "Nm:/Buttons#P6-Works",
					url "Nm:/Buttons#P7-Play"																	}
		for i = 1, 7 do
			go_set(Panels[i], TINTW, 0.73)
		end
	go_set("RenderHint#Quad", TINTW, 0.637)

	timer.delay( 0.2, true, function()																-- Play(Pause) Button
		if AudioPlaying ~= LastPlaying then
			sys.set_engine_throttle(not AudioPlaying, 0.25)
			label_set_text("Nm:/Buttons#L7-Play", AudioPlaying and "Pause" or "Play")
			LastPlaying = AudioPlaying
		end
	end )

	local SN, Dir = sys.get_sys_info().system_name, sys.get_save_file("Nemesis Works", "")			-- Works Button
	if SN == "Windows" then			WorksCmd = string_format("start \"\" \"%s\"", Dir)
	elseif SN == "Darwin" then		WorksCmd = "open " .. string.gsub(Dir, "%s", "\\ ")
	else							WorksCmd = "xdg-open " .. string.gsub(Dir, "%s", "\\ ")
	end

	local CreateUnit, _, HS = AcAudio.CreateUnit, AcAudio.CreateSource("/Viewer.wav")				-- HitSound
	for i = 1, 32 do				HitSounds[i] = CreateUnit(HS)
	end

	io.output( sys.get_save_file("Nemesis Works", "[Nemesis License]") )							-- License
	io.write ( sys.load_resource("/Viewer.license") )
	io.close ()

	if pcall( io.input, sys.get_save_file("Nemesis Works", "[Addon]") ) then						-- Addon
		local newHeader = table.concat{ HEADER, io.read("*a"), "\n" }
		if pcall(loadstring(newHeader)) then
			HEADER, Title = newHeader, "Nemesis with Addon"
			window.set_title(Title)
		end
	end
end

function update()
	if FumenLoaded then
		AudioPlaying = CheckPlaying(Audio)
			if AudioPlaying then
				UpdateCanvas( GetTime(Audio), true )
			end
		----
	end
end

function on_input(self, action_id, action)
	return true, (InputMode and InputModeFns[action_id] or ActionFns[action_id] or NIL)(action)
end